services:
  web_predict_car_prices:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: "postgres:15"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  postgres_data:
  redis_data:
