services:
  web_predict_car_prices:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: "postgres:15"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: